# Generated by Django 3.2.9 on 2023-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230218_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_create_opportunities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_delete_opportunities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_update_opportunities',
            field=models.BooleanField(default=False),
        ),
    ]
