# Generated by Django 3.2.9 on 2023-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
