# Generated by Django 3.2.9 on 2023-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
