# Generated by Django 3.2.9 on 2023-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_image_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='folder',
            field=models.CharField(choices=[('PROFILE', 'Profile'), ('OPPORTUNITY', 'Opportunity'), ('BLOG', 'Blog')], max_length=50, null=True),
        ),
    ]
