# Generated by Django 3.2.9 on 2023-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_image_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-date_added',)},
        ),
    ]
