# Generated by Django 3.2.9 on 2023-06-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20230512_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
