# Generated by Django 3.2.9 on 2022-12-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221203_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_length',
            field=models.FloatField(),
        ),
    ]
