# Generated by Django 3.2.9 on 2023-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='short summary'),
        ),
    ]
