# Generated by Django 3.2.9 on 2023-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Testing', max_length=300),
            preserve_default=False,
        ),
    ]
