# Generated by Django 3.2.9 on 2022-12-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_read_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_length',
            field=models.IntegerField(),
        ),
    ]
