# Generated by Django 3.2.9 on 2022-12-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_read_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_length',
            field=models.FloatField(),
        ),
    ]
