# Generated by Django 3.2.9 on 2023-01-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230124_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/posts'),
        ),
    ]
