# Generated by Django 3.2.9 on 2023-01-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
    ]
