# Generated by Django 3.2.9 on 2023-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_postimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_length',
            field=models.FloatField(null=True),
        ),
    ]
