# Generated by Django 3.2.9 on 2023-05-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_image_options'),
        ('blog', '0014_alter_post_cover_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.image'),
        ),
    ]
