# Generated by Django 3.2.9 on 2022-12-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['date_added', 'last_updated']},
        ),
    ]
