# Generated by Django 3.2.9 on 2022-12-18 03:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcast_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/podcast'),
        ),
    ]
