# Generated by Django 3.2.9 on 2022-12-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/organizations'),
        ),
    ]
