# Generated by Django 3.2.9 on 2023-01-05 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0003_alter_podcast_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='host',
        ),
        migrations.AddField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/guests'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='guests',
            field=models.ManyToManyField(related_name='podcasts', to='podcast.Guest'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='hosts',
            field=models.ManyToManyField(related_name='podcasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
