# Generated by Django 3.2.9 on 2022-12-07 10:12

from django.db import migrations, models
import django.db.models.deletion
import podcast.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20221206_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[podcast.validators.FileValidator(content_types=('audio/x-mp3', 'audio/mp4', 'audio/mpeg', 'application/ogg', 'audio/x-mp2'))]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='podcast.guest'),
        ),
    ]
