# Generated by Django 3.2.9 on 2022-12-07 14:05

from django.db import migrations, models
import django.db.models.deletion
import podcast.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20221207_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='podcast.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='podcast.organization'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/podcast', validators=[podcast.validators.FileValidator(content_types=('audio/x-mp3', 'audio/mp4', 'audio/mpeg', 'application/ogg', 'audio/x-mp2'))]),
        ),
    ]
