# Generated by Django 3.2.9 on 2023-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20230105_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='listens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
