# Generated by Django 3.2.9 on 2022-12-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_auto_20221207_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunity',
            old_name='company',
            new_name='organization',
        ),
    ]
