# Generated by Django 3.2.9 on 2022-12-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_rename_company_oportunity_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oportunity',
            new_name='Opportuinity',
        ),
    ]
