# Generated by Django 3.2.9 on 2023-01-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_auto_20230113_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='podcast.podcast'),
        ),
    ]
