# Generated by Django 3.2.9 on 2023-01-13 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_alter_host_podcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('user', 'date_added')},
        ),
        migrations.AddField(
            model_name='host',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
