# Generated by Django 3.2.9 on 2023-01-14 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0009_auto_20230113_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='podcast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='podcast.podcast'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.customuser'),
            preserve_default=False,
        ),
    ]
