# Generated by Django 3.2.9 on 2023-01-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_auto_20230114_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opportuinity',
            new_name='Opportunity',
        ),
    ]
