# Generated by Django 3.2.9 on 2023-01-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0012_guest_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/podcasts'),
        ),
    ]
