# Generated by Django 3.2.9 on 2023-04-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(choices=[('IT', 'Internship'), ('JL', 'Job listing'), ('SC', 'Scholarship')], default='IT', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(to='assets.Image')),
            ],
        ),
    ]
