# Generated by Django 3.2.9 on 2023-04-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_tag'),
        ('opportunities', '0002_rename_oportunity_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.tag'),
        ),
    ]
