# Generated by Django 3.2.9 on 2023-05-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunity_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ('-last_updated',)},
        ),
    ]
