# Generated by Django 3.2.9 on 2023-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20230512_0625'),
        ('opportunities', '0005_auto_20230510_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='category',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(to='assets.Tag'),
        ),
    ]
